[Interface]
PrivateKey = WP+czadXEgkKu2BSIyfYxlGQlNVrZMrU6fTZ1zKlVWE=
Address = 10.8.0.3/32
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = 2e1K3zPXdTmG5vwQdjmUZ6RlzDg6MVDjpnGc52t3pXE=
Endpoint = 24.86.192.209:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
